//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rout
    {
        public int rout_id { get; set; }
        public Nullable<int> p_rout_id { get; set; }
        public int tour_id { get; set; }
        public int bus_id { get; set; }
        public int point_start { get; set; }
        public int point_end { get; set; }
        public System.DateTime dtstart { get; set; }
        public System.DateTime dtend { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Point Point { get; set; }
        public virtual Point Point1 { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
